title: ludovicl.fr
name: ludovicl.fr
email: ludovic.lrds+blog@gmail.com
description: Ma curation webistique, du dev, des technos, du développement personnel,...
url: ludovicl.fr 
twitter_username: ludovicl
github_username:  ludovicl
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination Settings
paginate: 5
paginate_path: "/page:num/"

